name: Build Tomcat

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out tomcat-users.xml
      uses: actions/checkout@v2

    - name: List project files and java version
      run: |
        ls -ltr
        java -version

    - name: Check out the Tomcat repo
      uses: actions/checkout@v4.2.2
      with:
        repository: apache/tomcat # repository name with owner
        ref: main                 # the branch, tag, or SHA to checkout
        path: ./tomcat            # relative path under $GITHUB_WORKSPACE

    - name: Setup Java
      uses: actions/setup-java@v4.7.1
      with:
        distribution: oracle  # the distribution of Java to use
        java-version: 21      # the JDK version to make available on the path

    - name: List project files and java version
      run: |
        ls -ltr
        java - version

    - name: Copy tomcat-users.xml into Tomcat configuration directory
      run: cp -v tomcat-users.xml ./tomcat/conf/tomcat-users.xml

    - name: Compile Tomcat
      run: |
        cd ./tomcat
        ant
          
